# Generated by Django 4.2 on 2023-04-25 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='private_seed',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='userdata',
            name='public_seed',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
