# Generated by Django 4.2 on 2023-04-20 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='nonce',
            field=models.CharField(default=uuid.uuid4, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='nonce_expired',
            field=models.BooleanField(default=True),
        ),
    ]
