# Generated by Django 4.2 on 2023-04-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userdata_private_seed_userdata_public_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='private_seed',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='public_seed',
        ),
    ]
