# Generated by Django 4.2 on 2023-04-21 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userdata_nonce_userdata_nonce_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='nonce',
        ),
        migrations.CreateModel(
            name='NonceSignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('nonce', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
