# Generated by Django 4.2 on 2023-04-23 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_userdata_nonce_noncesignrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='role',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
