# Generated by Django 4.2 on 2023-04-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomhandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('public_seed', models.CharField(max_length=128)),
                ('private_seed', models.CharField(max_length=128)),
                ('signed_private_seed_base64', models.CharField(max_length=128)),
                ('chain', models.CharField(max_length=128)),
                ('index', models.PositiveBigIntegerField()),
            ],
        ),
    ]
