# Generated by Django 4.2 on 2023-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomhandler', '0002_extractednumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractednumber',
            name='number',
            field=models.CharField(max_length=128),
        ),
    ]
