# Generated by Django 4.2 on 2023-04-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomhandler', '0004_alter_extractednumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractednumber',
            name='chain',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='extractednumber',
            name='signed_private_seed_base64',
            field=models.CharField(max_length=256),
        ),
    ]
