# Generated by Django 4.2 on 2023-04-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomhandler', '0007_alter_extractednumber_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashchainindex',
            name='chain',
            field=models.CharField(default='0', unique=True),
        ),
    ]
