# Generated by Django 4.2 on 2023-04-25 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('randomhandler', '0008_alter_hashchainindex_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost')], default='PENDING', max_length=20)),
                ('reward_percentage', models.FloatField(default=0)),
                ('extracted_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='randomhandler.hashchainindex')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoinFlip',
            fields=[
                ('instantgame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='instantgame.instantgame')),
                ('outcome', models.CharField(choices=[('NONE', 'None'), ('HEAD', 'Head'), ('TAILS', 'Tails')], default='NONE', max_length=20)),
                ('bet', models.CharField(choices=[('NONE', 'None'), ('HEAD', 'Head'), ('TAILS', 'Tails')], default='NONE', max_length=20)),
            ],
            bases=('instantgame.instantgame',),
        ),
    ]
