# Generated by Django 4.2 on 2023-04-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomhandler', '0008_alter_hashchainindex_chain'),
        ('instantgame', '0002_instantgame_bet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantgame',
            name='extracted_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='randomhandler.extractednumber'),
        ),
    ]
