# Generated by Django 4.2 on 2023-04-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instantgame', '0003_alter_instantgame_extracted_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantGameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=16)),
                ('reward_percentage', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='instantgame',
            name='reward_percentage',
        ),
    ]
