# Generated by Django 4.2 on 2023-04-26 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instantgame', '0004_instantgamesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantgame',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instantgame.instantgamesettings'),
        ),
    ]
